/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./../src/router/404.vue')['default']
    App: typeof import('./../src/App.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    FindMe: typeof import('./../src/stations/FindMe.vue')['default']
    PageThree: typeof import('./../src/components/PageThree.vue')['default']
    PageTwo: typeof import('./../src/components/PageTwo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZArticle: typeof import('./../src/blog/ZArticle.vue')['default']
    ZBlog: typeof import('./../src/blog/ZBlog.vue')['default']
    ZBlogTagDisplay: typeof import('./../src/components/ZBlogTagDisplay.vue')['default']
    ZBulletComment: typeof import('./../src/components/ZBulletComment.vue')['default']
    ZBulletScreen: typeof import('./../src/components/ZBulletScreen.vue')['default']
    ZCarousel: typeof import('./../src/blog/ZCarousel.vue')['default']
    ZComment: typeof import('./../src/user/ZComment.vue')['default']
    ZComments: typeof import('./../src/user/ZComments.vue')['default']
    ZEmoji: typeof import('./../src/user/ZEmoji.vue')['default']
    ZFilter: typeof import('./../src/components/ZFilter.vue')['default']
    ZFooter: typeof import('./../src/layout/ZFooter.vue')['default']
    ZHeader: typeof import('./../src/layout/ZHeader.vue')['default']
    ZHome: typeof import('./../src/layout/ZHome.vue')['default']
    ZLayout: typeof import('./../src/layout/ZLayout.vue')['default']
    ZLefting: typeof import('./../src/user/ZLefting.vue')['default']
    ZLoading: typeof import('./../src/components/ZLoading.vue')['default']
    ZMultiPai: typeof import('./../src/user/ZMultiPai.vue')['default']
    ZReply: typeof import('./../src/user/ZReply.vue')['default']
    ZSider: typeof import('./../src/layout/ZSider.vue')['default']
    ZSignature: typeof import('./../src/global/ZSignature.vue')['default']
    ZStations: typeof import('./../src/stations/ZStations.vue')['default']
    ZTags: typeof import('./../src/components/ZTags.vue')['default']
    ZTimeline: typeof import('./../src/components/ZTimeline.vue')['default']
    ZTypography: typeof import('./../src/components/ZTypography.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
