/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./../src/components/error/404.vue')['default']
    DemoGrid: typeof import('./../src/components/findme/DemoGrid.vue')['default']
    DemoGridItem: typeof import('./../src/components/findme/DemoGridItem.vue')['default']
    DemoItem: typeof import('./../src/components/findme/DemoItem.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    EntryAnimation: typeof import('./../src/components/animation/EntryAnimation.vue')['default']
    FindMe: typeof import('./../src/components/findme/FindMe.vue')['default']
    Login: typeof import('./../src/components/user/login.vue')['default']
    PageThree: typeof import('./../src/components/home/PageThree.vue')['default']
    PageTwo: typeof import('./../src/components/home/PageTwo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YUANXIAO: typeof import('./../src/components/background/YUANXIAO.vue')['default']
    ZArticle: typeof import('./../src/components/blog/ZArticle.vue')['default']
    ZBlog: typeof import('./../src/components/blog/ZBlog.vue')['default']
    ZBlogTagDisplay: typeof import('./../src/components/blog/ZBlogTagDisplay.vue')['default']
    ZBulletComment: typeof import('./../src/components/lefting/ZBulletComment.vue')['default']
    ZBulletScreen: typeof import('./../src/components/lefting/ZBulletScreen.vue')['default']
    ZCarousel: typeof import('./../src/blog/ZCarousel.vue')['default']
    ZComment: typeof import('./../src/components/lefting/ZComment.vue')['default']
    ZComments: typeof import('./../src/components/lefting/ZComments.vue')['default']
    ZEmoji: typeof import('./../src/components/lefting/ZEmoji.vue')['default']
    ZFilter: typeof import('./../src/components/blog/ZFilter.vue')['default']
    ZFooter: typeof import('./../src/components/footer/ZFooter.vue')['default']
    ZHeader: typeof import('./../src/components/header/ZHeader.vue')['default']
    ZHome: typeof import('./../src/components/home/ZHome.vue')['default']
    ZLayout: typeof import('./../src/components/layout/ZLayout.vue')['default']
    ZLefting: typeof import('./../src/components/lefting/ZLefting.vue')['default']
    ZMultiPai: typeof import('./../src/components/lefting/ZMultiPai.vue')['default']
    ZReply: typeof import('./../src/components/lefting/ZReply.vue')['default']
    ZSectionNav: typeof import('./../src/components/blog/ZSectionNav.vue')['default']
    ZSignature: typeof import('./../src/components/signature/ZSignature.vue')['default']
    ZTags: typeof import('./../src/components/blog/ZTags.vue')['default']
    ZTimeline: typeof import('./../src/components/blog/ZTimeline.vue')['default']
    ZTypography: typeof import('./../src/components/findme/ZTypography.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
