/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogDialog: typeof import('./../src/components/blog/BlogDialog.vue')['default']
    BlogTemplate: typeof import('./../src/components/template/BlogTemplate.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    PageOne: typeof import('./../src/components/home/PageOne.vue')['default']
    PageThree: typeof import('./../src/components/home/PageThree.vue')['default']
    PageTwo: typeof import('./../src/components/home/PageTwo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YUANXIAO: typeof import('./../src/components/background/YUANXIAO.vue')['default']
    ZBlog: typeof import('./../src/components/blog/ZBlog.vue')['default']
    ZBulletComment: typeof import('./../src/components/lefting/ZBulletComment.vue')['default']
    ZBulletScreen: typeof import('./../src/components/lefting/ZBulletScreen.vue')['default']
    ZFilter: typeof import('./../src/components/blog/ZFilter.vue')['default']
    ZFooter: typeof import('./../src/components/footer/ZFooter.vue')['default']
    ZHeader: typeof import('./../src/components/header/ZHeader.vue')['default']
    ZHome: typeof import('./../src/components/home/ZHome.vue')['default']
    ZLayout: typeof import('./../src/components/layout/ZLayout.vue')['default']
    ZLefting: typeof import('./../src/components/lefting/ZLefting.vue')['default']
    ZTag: typeof import('./../src/components/blog/ZTag.vue')['default']
    ZTags: typeof import('./../src/components/blog/ZTags.vue')['default']
    ZTimeline: typeof import('./../src/components/blog/ZTimeline.vue')['default']
  }
}
