/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./../src/components/error/404.vue')['default']
    BlogTemplate: typeof import('./../src/components/template/BlogTemplate.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EntryAnimation: typeof import('./../src/components/animation/EntryAnimation.vue')['default']
    FindMe: typeof import('./../src/components/findme/FindMe.vue')['default']
    PageThree: typeof import('./../src/components/home/PageThree.vue')['default']
    PageTwo: typeof import('./../src/components/home/PageTwo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YUANXIAO: typeof import('./../src/components/background/YUANXIAO.vue')['default']
    ZBlog: typeof import('./../src/components/blog/ZBlog.vue')['default']
    ZBlogListDisplay: typeof import('./../src/components/blog/ZBlogListDisplay.vue')['default']
    ZBlogTagDisplay: typeof import('./../src/components/blog/ZBlogTagDisplay.vue')['default']
    ZBulletComment: typeof import('./../src/components/lefting/ZBulletComment.vue')['default']
    ZBulletScreen: typeof import('./../src/components/lefting/ZBulletScreen.vue')['default']
    ZComment: typeof import('./../src/components/lefting/ZComment.vue')['default']
    ZFilter: typeof import('./../src/components/blog/ZFilter.vue')['default']
    ZFooter: typeof import('./../src/components/footer/ZFooter.vue')['default']
    ZHeader: typeof import('./../src/components/header/ZHeader.vue')['default']
    ZHome: typeof import('./../src/components/home/ZHome.vue')['default']
    ZLayout: typeof import('./../src/components/layout/ZLayout.vue')['default']
    ZLefting: typeof import('./../src/components/lefting/ZLefting.vue')['default']
    ZMarkdownPreview: typeof import('./../src/components/template/ZMarkdownPreview.vue')['default']
    ZSignature: typeof import('./../src/components/signature/ZSignature.vue')['default']
    ZTags: typeof import('./../src/components/blog/ZTags.vue')['default']
    ZTimeline: typeof import('./../src/components/blog/ZTimeline.vue')['default']
  }
}
