/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogTemplate: typeof import('./components/template/BlogTemplate.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    PageOne: typeof import('./components/home/PageOne.vue')['default']
    PageThree: typeof import('./components/home/PageThree.vue')['default']
    PageTwo: typeof import('./components/home/PageTwo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YUANXIAO: typeof import('./components/background/YUANXIAO.vue')['default']
    ZBulletComment: typeof import('./components/lefting/ZBulletComment.vue')['default']
    ZBulletScreen: typeof import('./components/lefting/ZBulletScreen.vue')['default']
    ZFooter: typeof import('./components/footer/ZFooter.vue')['default']
    ZHeader: typeof import('./components/header/ZHeader.vue')['default']
    ZHome: typeof import('./components/home/ZHome.vue')['default']
    ZLayout: typeof import('./components/layout/ZLayout.vue')['default']
    ZLefting: typeof import('./components/lefting/ZLefting.vue')['default']
  }
}
